"""
Reference data loader for theme-based preset suggestions.

Architecture:
- data/food_references.json   : curated food photography presets
- data/street_references.json : curated street photography presets (coming soon)

Web scraping is intentionally NOT used at runtime because major photography sites
block automated requests (HTTP 403). Instead, reference data is pre-curated and
stored as JSON, allowing fast lookups with no external dependencies.

Future: data files can be regenerated by running this module directly with
appropriate API keys for services that offer proper data access.
"""

import json
from pathlib import Path

DATA_DIR = Path(__file__).parent / "data"

_cache: dict[str, dict] = {}


def load_theme_references(theme: str) -> dict:
    """Load curated reference presets for a given theme."""
    if theme in _cache:
        return _cache[theme]
    path = DATA_DIR / f"{theme}_references.json"
    if not path.exists():
        return {}
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    _cache[theme] = data
    return data


def get_preset_for_keyword(keyword: str, theme: str = "food") -> tuple[str | None, dict | None]:
    """
    Return (preset_name, preset_params) for the best matching keyword in a theme.
    Returns (None, None) if no match found.
    """
    refs = load_theme_references(theme)
    if not refs:
        return None, None

    keyword_map = refs.get("keyword_map", {})
    presets = refs.get("presets", {})

    kw_lower = keyword.lower()
    for kw, preset_name in keyword_map.items():
        if kw in kw_lower:
            preset = presets.get(preset_name)
            if preset:
                return preset_name, preset

    return None, None


def list_presets_for_theme(theme: str) -> dict[str, dict]:
    """Return all presets for a given theme."""
    refs = load_theme_references(theme)
    return refs.get("presets", {})


def suggest_preset_by_tags(tags: list[str], theme: str = "food") -> tuple[str | None, dict | None]:
    """Find best matching preset by style tags."""
    refs = load_theme_references(theme)
    presets = refs.get("presets", {})
    if not presets:
        return None, None

    best_name = None
    best_score = 0
    for name, preset in presets.items():
        preset_tags = set(preset.get("style_tags", []))
        score = len(preset_tags & set(t.lower() for t in tags))
        if score > best_score:
            best_score = score
            best_name = name

    if best_name:
        return best_name, presets[best_name]
    return None, None


def get_all_themes() -> list[str]:
    """Return list of themes with available reference data."""
    return [p.stem.replace("_references", "") for p in DATA_DIR.glob("*_references.json")]


if __name__ == "__main__":
    # Quick diagnostic
    for theme in get_all_themes():
        refs = load_theme_references(theme)
        presets = refs.get("presets", {})
        print(f"\nTheme: {theme} — {len(presets)} presets")
        for name, p in presets.items():
            tags = ", ".join(p.get("style_tags", [])[:4])
            print(f"  {name}: [{tags}]")
